### ISSUE TITLE
Incompatible with ReSharper 23.3

### ISSUE THREAD

**Issue by kyle-csg** [phasTrak/AsyncApostle#11]
Could you please release a new version that is compatible with ReSharper 23.3?

![image](https://github.com/phasTrak/AsyncApostle/assets/149391562/0a883f90-5185-488b-87f9-c86fbd22c647)

**Comment by AndreyRavkov** [comment]
+1

**Comment by ristogod** [comment]
Sorry. It's usually out there sooner, but made some organizational changes and working with JetBrains to resolve the uploading. It should be uploaded today and hopefully approved by Monday, 12/18/2023. Thanks for your patience.

**Comment by FXZFun** [comment]
Version 2023.3.0 is now available on the plugin marketplace, compatible with the latest ReSharper and Rider versions.
ReSharper: [https://plugins.jetbrains.com/plugin/17945-asyncapostle/](https://plugins.jetbrains.com/plugin/17945-asyncapostle/)
Rider: [https://plugins.jetbrains.com/plugin/17946-asyncapostle/](https://plugins.jetbrains.com/plugin/17946-asyncapostle/)
