### ISSUE TITLE
Support for Resharper 2024.2

### ISSUE THREAD

**Issue by DevEngineReq** [phasTrak/AsyncApostle#13]
Please ensures compatibility with ReSharper 2024.2

**Comment by FXZFun** [comment]
AsyncApostle 2024.2.1 has been released and is now available for ReSharper: https://plugins.jetbrains.com/plugin/17945-asyncapostle
The Rider plugin is still under review but should be available within a day or two.

**Comment by Mike-E-angelo** [comment]
Thank you very much!  I can confirm I was able to update to the latest version. 🙏🙏🙏
