### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by tresoldigiorgio** [phasTrak/AsyncApostle#2]
I'm not able to install plugin in rider 2021.2.2.
I've tried to search plugin in marketplace but I don't find it.
I've tried to install from disk but when I restart rider the plugin disappear.
Thank you in advance
Giorgio

**Comment by ristogod** [comment]
Yes, JetBrains flagged the plugin due to it having an "inadequate" description. I've since updated the description and uploaded an update to JetBrains in hopes that they will approve it.

**Comment by tresoldigiorgio** [comment]
Do you know why plugin disappear if I add it from disk using zip file?

**Comment by AndreyRavkov** [comment]
it's approved. i successfully installed it to my rider 2021.2

**Comment by tresoldigiorgio** [comment]
I've the same problem...but I think its only mine. :-( 
thanks!

**Comment by tresoldigiorgio** [comment]
No one in my organization can install the plugin. 
I've found a similar issue on rider support https://youtrack.jetbrains.com/issue/RIDER-66631.
Seems to be a problem with plugin zip package because the zip structure not match the correct explained here https://www.jetbrains.com/help/resharper/sdk/Products/Rider.html#plugin-packaging.
I don't now how Andrey not have the same problem....

**Comment by ristogod** [comment]
@tresoldigiorgio 

I'm not exactly sure why it's does or doesn't work for you. I'm just learning this code base as I go, as was a copy.

The .nuke project include with this was what I rant to get it to build into its current format, where the zip didn't seem to correspond with the stated documentation you showed.

I've updated the version and am built the zip manually according to documentation and have uploaded a new version. After JetBrains gives approval, you can try again and hopefully that resolves the issue.

**Comment by AndreyRavkov** [comment]
@tresoldigiorgio 
I'm sorry. Looks like i have such problem. But it was installed from the marketplace and working till the next rider reset :(
I've tried via marketplace and zip package with the same result. Now, I'm trying with EAP for 2021.3 version and I can't install it.

**Comment by tresoldigiorgio** [comment]
I've just tried the last version of plugin released 2 days ago but it doesn't work. After installation and restart the plugin disappear.

**Comment by SephVin** [comment]
Same for me in Rider 2021.3. After reset plugin disappear

**Comment by AndreyRavkov** [comment]
> Hi! Same for me in Rider 2021.3. After reset plugin disappear

+1

**Comment by ristogod** [comment]
After the previous release with the feedback about not installing correctly into Rider, I attempted to update structure of the zip I have to upload to JetBrains.

I don't use Rider myself (VS2022/R#). I did install it and confirmed I see the results being reported.

I may have incorrectly structured the zip again. Odd Jetbrains doesn't indicate to me it doesn't work. I'm not sure how they verify. 

So I tried again and pushed out another release. So look and see if it resolves the issue (after it's released). If not, I'll have to investigate further.

**Comment by SephVin** [comment]
Hi! I've tried new version (2021.3.0.1). The plugin doesn't work. After installation and restart the plugin disappear.

**Comment by ProXAlex** [comment]
> Привет! Пробовал новую версию (2021.3.0.1). Плагин не работает. После установки и перезапуска плагин исчезнет.

Same

**Comment by ProXAlex** [comment]
> Hi! I've tried new version (2021.3.0.1). The plugin doesn't work. After installation and restart the plugin disappear.

Same

**Comment by g1n** [comment]
``

**Comment by g1n** [comment]
Hi! Work fine when zip is structured like this:
```
+ plugin-root-folder
    + lib
        + plugin.jar
            + META-INF
                - plugin.xml
    + dotnet
        - plugin.dll
```

But now structured like this:
```
+ plugin-root-folder
    + META-INF
        - plugin.xml
    - plugin.nupkg
```
See same issue https://github.com/Abc-Arbitrage/Abc.MoqComplete/issues/25

**Comment by AndreyRavkov** [comment]
Hello,
version 2021.3.1.1 is installed in Rider and doesn't disappear after the restart. But it's not working, e.g. suggestions, bugs and etc. Could somebody try?

**Comment by g1n** [comment]
@ristogod zip is incorrected
please, rename net472 to dotnet

I have tried build plugin and manually create zip archive. Work fine when zip is structured like this:

```
+ plugin-root-folder
    + lib
        + plugin.jar
            + META-INF
                - plugin.xml
    + dotnet //in version 2021.3.1.1 this directory has name net472, but should dotnet
        - plugin.dll
```

**Comment by ProXAlex** [comment]
> Hello, version 2021.3.1.1 is installed in Rider and doesn't disappear after the restart. But it's not working, e.g. suggestions, bugs and etc. Could somebody try?

same

**Comment by ristogod** [comment]
Taking @g1n 's suggestion and also updated to Resharper.SDK 2021.3.2. Latest is uploaded with those changes and should be available soon. Let me know if it still isn't working after.

**Comment by AndreyRavkov** [comment]
The version 2021.3.2.0 is working in Rider.
